Update Fourier-Metalens.ipynb
Changed the first argument of every call to opt.plot2D() to True. Not sure why, but this was causing the following error message:
AttributeError: 'IndexedSource' object has no attribute 'center'